### ISSUE TITLE
Deadlock eventually occurs in `JdkHttpClient` for certain requests

### ISSUE THREAD

**Issue by Billzabob** [http4s/http4s-jdk-http-client#200] opened 2020-04-01 19:30 UTC
I am currently sharing the Java 8 HTTP client to create both the WebSocket client and the HTTP client. I make a single request with the HTTP client followed by connecting to a WebSocket and sending messages periodically. Eventually (always around 400 seconds later), everything hangs and CPU usage is locked at 100%.

This doesn't occur if:
- I create a separate client and WebSocket client using `.simple[IO]`
- I don't make the initial request with the client
- I request other URLs with the client

Since it doesn't happen with every URL, I'm assuming it has something to do with the endpoint I'm hitting. It gives the following response:
```
Response(
  status=200,
  headers=Headers(
    cf-cache-status: DYNAMIC,
    cf-ray: 57d4a1eb4eaaa062-SLC,
    connection: keep-alive,
    content-type: application/json,
    date: Wed, 01 Apr 2020 19:14:20 GMT,
    expect-ct: max-age=604800,
    report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct",
    server: cloudflare,
    set-cookie: <REDACTED>,
    set-cookie: <REDACTED>,
    strict-transport-security: max-age=31536000; includeSubDomains,
    transfer-encoding: chunked,
    via: 1.1 google,
    x-envoy-upstream-service-time: 26,
    x-ratelimit-bucket: 41f9cd5d28af77da04563bcb1d67fdfd,
    x-ratelimit-limit: 2,
    x-ratelimit-remaining: 1,
    x-ratelimit-reset: 1585768466,
    x-ratelimit-reset-after: 5
  )
)

{
  "url": "wss://gateway.discord.gg",
  "shards": 1,
  "session_start_limit": {
    "total": 1000,
    "remaining": 992,
    "reset_after": 23572680
  }
}
```

I tried to put together a minimized example of what I'm seeing here:
```scala
import cats.effect._
import cats.implicits._
import fs2.Stream
import java.net.http.HttpClient
import org.http4s.client.jdkhttpclient._
import org.http4s.client.jdkhttpclient.WSFrame._
import org.http4s._
import org.http4s.headers._
import org.http4s.implicits._
import scala.concurrent.duration._

object Main extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    IO(HttpClient.newHttpClient).map(client => (JdkHttpClient[IO](client), JdkWSClient[IO](client))).flatMap {
      case (client, wsClient) =>
        client.expect[String](Request[IO](uri = uri"https://discordapp.com/api/gateway/bot", headers = Headers.of(headers))) >> connection(wsClient)
          .compile
          .drain
          .as(ExitCode.Success)
    }
  }

  // Removed since it's private info
  val token: String = ???

  val headers =
    Authorization(Credentials.Token("Bot".ci, token))

  def connection(wsClient: WSClient[IO]) =
    Stream
      .resource(wsClient.connectHighLevel(WSRequest(uri"wss://echo.websocket.org")))
      .flatMap { connection =>
        printResponses(connection).concurrently(
          Stream
            .awakeEvery[IO](1.seconds)
            .evalMap(time => connection.send(Text(s"${time.toSeconds} seconds")))
        )
      }

  def printResponses(connection: WSConnectionHighLevel[IO]): Stream[IO, Unit] = {
    connection.receiveStream
      .collect {
        case Text(data, _) => data
      }
      .evalMap(s => IO(println(s)))
  }

}
```

This prints out:
```
1 seconds
2 seconds
3 seconds
4 seconds
5 seconds
6 seconds
7 seconds
8 seconds
...
393 seconds
394 seconds
395 seconds
396 seconds
397 seconds
```
And then it hangs and CPU usage is stuck at 100%

**Comment by Billzabob** [comment] 2020-04-01 20:02
I was able to narrow this down even further. It seems to just be related to the client. The following code also hangs and pegs CPU at 100% after about 460 seconds:
```scala
import cats.effect._
import cats.implicits._
import fs2.Stream
import org.http4s._
import org.http4s.client.jdkhttpclient._
import org.http4s.headers._
import org.http4s.implicits._
import scala.concurrent.duration._

object Main2 extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    JdkHttpClient.simple[IO].flatMap { client =>
      Stream
        .awakeEvery[IO](5.seconds)
        .evalTap(_ => client.expect[String](Request[IO](uri = uri"https://discordapp.com/api/gateway/bot", headers = Headers.of(headers))))
        .evalTap(time => IO(println(s"${time.toSeconds} seconds")))
        .compile
        .drain
        .as(ExitCode.Success)
    }
  }

  val token = ???

  val headers =
    Authorization(Credentials.Token("Bot".ci, token))

}
```

**Comment by ChristopherDavenport** [comment] 2020-04-01 20:05
Since this is associated in some way with the JDK, which JDK is being used?

**Comment by Billzabob** [comment] 2020-04-01 20:10
@ChristopherDavenport I'm using JDK 11

**Comment by Billzabob** [comment] 2020-04-01 20:15
Any idea what it could be about this particular response that causes this? I tried testing this against a few other URLs and wasn't able to reproduce the issue.

**Comment by amesgen** [comment] 2020-04-01 20:54
How do I create such a token? I created a discord "application" and got a token, but I get 401 unauthorized.

**Comment by amesgen** [comment] 2020-04-01 21:17
I can confirm that increased cpu usage does *not* happen on e.g. `https://discordapp.com` (no `api/gateway/bot`).

Can you test if this happens with #191 ? It is the only thing I can think of right now.

**Comment by Billzabob** [comment] 2020-04-01 22:17
I'm not sure why you're getting a 401. It's been a while since I created my bot but I think that's all I did. I just ran it using `java.net.http.HttpClient` directly and it never froze. I also am running it with #191 right now and so far it's made it further than before so maybe that's the problem. I'll leave it running and let you know if it ever hangs 👍

**Comment by Billzabob** [comment] 2020-04-01 22:22
It's hung again :( After running for 770 seconds it stopped and once again I'm seeing 100% CPU usage.

**Comment by amesgen** [comment] 2020-04-01 22:26
Ah, I thought I had to change `"Bot".ci`, now it works. Now staring at CPU usage...

**Comment by amesgen** [comment] 2020-04-01 22:46
It has been running for 1300 seconds and I noticed nothing suspicious about CPU or memory usage. I am on master, not on #191.

My Java version:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
```
Can you test it with this version?

**Comment by amesgen** [comment] 2020-04-01 22:51
Maybe [JDK-8221395](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8221395) is the reason?

**Comment by Billzabob** [comment] 2020-04-01 23:39
I was hopeful. I tried it with that JDK but it's still freezing up for me :( This time it did at 430 seconds.

**Comment by amesgen** [comment] 2020-04-01 23:47
Can you turn on [logging](https://stackoverflow.com/questions/53215038/how-to-log-request-response-using-java-net-http-httpclient/53215443#53215443)?

**Comment by amesgen** [comment] 2020-04-02 00:17
Uh, now it froze for me, after 4010 seconds (accidentally cancelled the first run after ~1800 seconds).

**Comment by Billzabob** [comment] 2020-04-02 00:59
Wow yours took way longer to freeze than any of my runs. Glad I'm not the only one able to produce the bug though. I won't be able to mess with this again until tomorrow, but I'll try running it with logging then.

**Comment by amesgen** [comment] 2020-04-02 02:43
After ~8000 seconds, I got another freeze, and the following lines were spammed again and again:
```
DEBUG: [HttpClient-1-Worker-0] [8175s 935ms] SSL Writer(SocketTube(5)) handshaking
DEBUG: [HttpClient-1-Worker-0] [8175s 935ms] SSL Writer(SocketTube(5)) wrapping 0 bytes
DEBUG: [HttpClient-1-Worker-0] [8175s 935ms] SSL Writer(SocketTube(5)) SSLResult: Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
DEBUG: [HttpClient-1-Worker-0] [8175s 935ms] SSL Writer(SocketTube(5)) OK => produced: 0 bytes into 0, not wrapped: 0
DEBUG: [HttpClient-1-Worker-0] [8175s 935ms] SSL Writer(SocketTube(5)) wrapBuffer returned Status = OK HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
```
I will try to look into this tomorrow.

**Comment by rossabaker** [comment] 2020-04-02 02:54
Looks a little like https://github.com/http4s/blaze/pull/359.

**Comment by amesgen** [comment] 2020-04-02 03:29
Indeed, the discord API endpoint provides TLS 1.3.

@Billzabob can you test with TLS 1.3 disabled? Like this:
```scala
for {
  sslParams <- IO {
    val ssl = javax.net.ssl.SSLContext.getDefault()
    val params = ssl.getDefaultSSLParameters()
    params.setProtocols(Array("TLSv1.2"))
    params
  }
  javaclient <- IO(java.net.http.HttpClient.newBuilder().sslParameters(sslParams).build())
  client = JdkHttpClient[IO](javaclient)
  _ <- Stream
    .awakeEvery[IO](5.seconds)
    .evalTap(_ =>
      client.expect[String](
        Request[IO](
          uri = uri"https://discordapp.com/api/gateway/bot",
          headers = Headers.of(headers)
        )
      )
    )
    .evalTap(time => IO(println(s"${time.toSeconds} seconds")))
    .compile
    .drain
} yield ExitCode.Success
```
And also with Java 14?

**Comment by Billzabob** [comment] 2020-04-02 15:54
So far it's been running for 1800 seconds with the SSL change so maybe that's it! I'll leave it running for a while to make sure and then I'll try Java 14.

**Comment by Billzabob** [comment] 2020-04-02 16:51
Running with Java 14 (and without the custom SSL parameters) and it also has made it much further. Currently, it's at 2400 seconds. Thanks for helping me track this down. I guess it's not really a change to this repo though, it's a JDK bug so sorry for wasting your time but thanks a bunch for helping me track it down.

**Comment by amesgen** [comment] 2020-04-02 16:55
No problem! We will add it to the documentation.

**Comment by amesgen** [comment] 2020-04-02 17:47
@Billzabob If you have the time: Can you try to reproduce the deadlock in "pure Java"?
```java
import java.net.*;
import java.net.http.*;
import java.util.*;

class Main {
  public static void main(String[] args) throws Exception {
    System.out.println("starting");
    var http = HttpClient.newHttpClient();
    var token = args[0];
    var req = HttpRequest.newBuilder()
                  .uri(URI.create("https://discordapp.com/api/gateway/bot"))
                  .header("Authorization", "Bot " + token)
                  .build();
    int s = 0;
    while (true) {
      Thread.sleep(5000);
      s += 5;
      var res = http.send(req, HttpResponse.BodyHandlers.ofString());
      System.out.println("status code " + res.statusCode());
      System.out.println(s);
    }
  }
}
```
Run with  `javac Main.java && java Main "token"`.

**Comment by Billzabob** [comment] 2020-04-02 22:53
Bad news, I'm currently at 9755 seconds without hanging... I'm using your pure Java example on JDK 11.0.6.

**Comment by Billzabob** [comment] 2020-04-02 22:53
I guess it must be something to do with the way the library uses the Java HttpClient that exposes the bug.

**Comment by amesgen** [comment] 2020-04-02 23:03
Yeah, I am at 17930 seconds. Yay, more debugging!

**Comment by Billzabob** [comment] 2020-04-03 02:34
Did some more messing around and put this together to try and mimic what your client does without actually using it:
```scala
import cats.effect._
import cats.implicits._
import fs2._
import fs2.interop.reactivestreams._
import java.net.http._
import java.nio.ByteBuffer
import java.util.concurrent.Flow
import org.http4s._
import org.http4s.headers._
import org.http4s.implicits._
import org.reactivestreams.FlowAdapters
import scala.concurrent.duration._
import scala.jdk.CollectionConverters._
import java.net.URI
import java.net.http.HttpResponse.BodyHandlers
import java.util.concurrent._
import java.util.function.BiFunction

object Main extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    IO(HttpClient.newHttpClient()).flatMap { client =>
    Stream
      .awakeEvery[IO](5.seconds)
      .evalTap(_ => makeRequest(client).flatMap(a => IO(println(a.status))))
      .evalTap(time => IO(println(s"${time.toSeconds} seconds")))
      .compile
      .drain
    }.as(ExitCode.Success)
  }

  val token = ???

  val headers =
    Authorization(Credentials.Token("Bot".ci, token))

  def makeRequest(client: HttpClient): IO[Response[IO]] = {
    val request = HttpRequest.newBuilder().uri(URI.create("https://discordapp.com/api/gateway/bot")).header("Authorization", s"Bot $token").build()
    val response = IO(client.sendAsync(request, BodyHandlers.ofPublisher()))
    fromCompletableFuture(response).flatMap(convertResponse)
  }

  def convertResponse(res: HttpResponse[Flow.Publisher[java.util.List[ByteBuffer]]]): IO[Response[IO]] =
    IO.fromEither(Status.fromInt(res.statusCode)).map { status =>
      Response(
        status = status,
        headers = Headers(res.headers.map.asScala.flatMap {
          case (k, vs) => vs.asScala.map(Header(k, _))
        }.toList),
        httpVersion = res.version match {
          case HttpClient.Version.HTTP_1_1 => HttpVersion.`HTTP/1.1`
          case HttpClient.Version.HTTP_2 => HttpVersion.`HTTP/2.0`
        },
        body = FlowAdapters
          .toPublisher(res.body)
          .toStream[IO]
          .flatMap(bs =>
            Stream.fromIterator[IO](bs.asScala.map(Chunk.byteBuffer).iterator).flatMap(Stream.chunk)
          )
      )
    }

  def fromCompletableFuture[A](fcf: IO[CompletableFuture[A]]): IO[A] =
    fcf.flatMap { cf =>
      IO.cancelable { cb =>
        cf.handle[Unit](new BiFunction[A, Throwable, Unit] {
          override def apply(result: A, err: Throwable): Unit = err match {
            case null => cb(Right(result))
            case _: CancellationException => ()
            case ex: CompletionException if ex.getCause ne null => cb(Left(ex.getCause))
            case ex => cb(Left(ex))
          }
        })
        IO(cf.cancel(true)).void
      }
    }
}
```

I've run it twice now and both times it fails with this exception after ~1200 seconds:
```
java.io.IOException: too many concurrent streams
        at java.net.http/jdk.internal.net.http.Http2Connection.reserveStream(Http2Connection.java:440)
        at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:103)
        at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:89)
        at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:299)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:431)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:336)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:328)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:346)
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:292)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Think this is related?

**Comment by amesgen** [comment] 2020-04-03 02:48
I think that is a different issue: the body of the response is not consumed, to the connection is kept open.

**Comment by amesgen** [comment] 2020-04-03 03:15
I can't reproduce your error above, but I think this should fix it:
```diff
diff --git a/core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala b/core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
index 9f0f93f..14b1471 100644
--- a/core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
+++ b/core/src/main/scala/org/http4s/client/jdkhttpclient/JdkHttpClient.scala
@@ -1,10 +1,5 @@
 package org.http4s.client.jdkhttpclient
 
-import cats.ApplicativeError
-import cats.effect._
-import cats.implicits._
-import fs2.interop.reactivestreams._
-import fs2.{Chunk, Stream}
 import java.net.URI
 import java.net.http.HttpRequest.BodyPublishers
 import java.net.http.HttpResponse.BodyHandlers
@@ -12,6 +7,13 @@ import java.net.http.{HttpClient, HttpRequest, HttpResponse}
 import java.nio.ByteBuffer
 import java.util
 import java.util.concurrent.Flow
+
+import cats.ApplicativeError
+import cats.effect._
+import cats.implicits._
+import fs2.concurrent.SignallingRef
+import fs2.interop.reactivestreams._
+import fs2.{Chunk, Stream}
 import org.http4s.client.Client
 import org.http4s.client.jdkhttpclient.compat.CollectionConverters._
 import org.http4s.internal.fromCompletionStage
@@ -58,34 +60,43 @@ object JdkHttpClient {
         (if (headers.isEmpty) rb else rb.headers(headers: _*)).build
       }
 
-    def convertResponse(res: HttpResponse[Flow.Publisher[util.List[ByteBuffer]]]): F[Response[F]] =
-      F.fromEither(Status.fromInt(res.statusCode)).map { status =>
-        Response(
-          status = status,
-          headers = Headers(res.headers.map.asScala.flatMap {
-            case (k, vs) => vs.asScala.map(Header(k, _))
-          }.toList),
-          httpVersion = res.version match {
-            case HttpClient.Version.HTTP_1_1 => HttpVersion.`HTTP/1.1`
-            case HttpClient.Version.HTTP_2 => HttpVersion.`HTTP/2.0`
-          },
-          body = FlowAdapters
-            .toPublisher(res.body)
-            .toStream[F]
-            .flatMap(bs =>
-              Stream.fromIterator(bs.asScala.map(Chunk.byteBuffer).iterator).flatMap(Stream.chunk)
-            )
-        )
-      }
+    def convertResponse(
+        res: HttpResponse[Flow.Publisher[util.List[ByteBuffer]]]
+    ): Resource[F, Response[F]] =
+      Resource(
+        (F.fromEither(Status.fromInt(res.statusCode)), SignallingRef[F, Boolean](false)).mapN {
+          case (status, signal) =>
+            Response(
+              status = status,
+              headers = Headers(res.headers.map.asScala.flatMap {
+                case (k, vs) => vs.asScala.map(Header(k, _))
+              }.toList),
+              httpVersion = res.version match {
+                case HttpClient.Version.HTTP_1_1 => HttpVersion.`HTTP/1.1`
+                case HttpClient.Version.HTTP_2 => HttpVersion.`HTTP/2.0`
+              },
+              body = FlowAdapters
+                .toPublisher(res.body)
+                .toStream[F]
+                .flatMap(bs =>
+                  Stream
+                    .fromIterator(bs.asScala.map(Chunk.byteBuffer).iterator)
+                    .flatMap(Stream.chunk)
+                    .interruptWhen(signal)
+                )
+            ) -> F.unit
+        }
+      )
 
     Client[F] { req =>
-      Resource.liftF(
-        convertRequest(req)
-          .flatMap(r =>
-            fromCompletionStage(F.delay(jdkHttpClient.sendAsync(r, BodyHandlers.ofPublisher)))
-          )
-          .flatMap(convertResponse)
-      )
+      Resource
+        .liftF(
+          convertRequest(req)
+            .flatMap(r =>
+              fromCompletionStage(F.delay(jdkHttpClient.sendAsync(r, BodyHandlers.ofPublisher)))
+            )
+        )
+        .flatMap(convertResponse)
     }
   }
```

**Comment by amesgen** [comment] 2020-04-03 03:17
I corrected the diff, sry.

**Comment by amesgen** [comment] 2020-04-03 04:53
Randomly, I got the freezes much faster than before, which made debugging much easier. I think this issue is somehow related to fs2-reactive-streams, because if I use `BodyHandlers.ofByteArray` instead of `BodyHandlers.ofPublisher`, I get no freezes locally.

Branch: https://github.com/amesgen/http4s-jdk-http-client/tree/weird-deadlock-stuff

**Comment by Billzabob** [comment] 2020-04-03 05:01
That makes sense and your fix makes sense, but I still got the same error after running it again with that change somehow.

**Comment by Billzabob** [comment] 2020-04-03 05:35
That branch froze up for me too :( 430 seconds in

**Comment by amesgen** [comment] 2020-04-03 05:39
I also got a freeze after 380 seconds, just after I cancelled the previous run which was 2000 seconds in...

So fs2-reactive-streams is not the culprit...

**Comment by amesgen** [comment] 2020-04-03 05:41
There really is not much code left in comparison to the (non-freezing) plain Java version, I will try to create a minimal example tomorrow.

**Comment by amesgen** [comment] 2020-04-03 20:26
Ok, "good" news: The freeze issue is not http4s-related, I got a freeze with this code:

<details>
<summary>Code (HTTP 1.1)</summary>

```scala
import java.net.URI
import java.net.http.HttpClient.Version
import java.net.http.HttpRequest.BodyPublishers
import java.net.http.HttpResponse.BodyHandlers
import java.net.http.{HttpClient, HttpRequest}
import java.time.Instant
import java.util.concurrent.{CancellationException, CompletionException, CompletionStage}

import cats.effect._
import cats.effect.implicits._
import cats.implicits._
import fs2.Stream

import scala.concurrent.duration._

object Main extends IOApp {

  override def run(args: List[String]): IO[ExitCode] =
    for {
      client <- IO(HttpClient.newHttpClient())
      runRequest = fromCompletionStage(
        IO(
          client.sendAsync(
            HttpRequest
              .newBuilder()
              .uri(URI.create("https://discordapp.com/api/gateway/bot"))
              .method("GET", BodyPublishers.noBody())
              .header("Authorization", s"Bot $token")
              .version(Version.HTTP_1_1)
              .build(),
            BodyHandlers.ofString()
          )
        )
      )
      _ <- Stream
        .awakeEvery[IO](5.seconds)
        .evalTap(_ => runRequest.flatMap(s => IO(println(s))))
        .evalTap(time => IO(println(s"[${Instant.now()}] ${time.toSeconds} seconds")))
        .compile
        .drain
    } yield ExitCode.Success

  def fromCompletionStage[F[_], CF[x] <: CompletionStage[x], A](
      fcs: F[CF[A]]
  )(implicit F: Concurrent[F], CS: ContextShift[F]): F[A] =
    fcs.flatMap { cs =>
      F.async[A] { cb =>
          cs.handle[Unit] { (result, err) =>
            err match {
              case null => cb(Right(result))
              case _: CancellationException => ()
              case ex: CompletionException if ex.getCause ne null => cb(Left(ex.getCause))
              case ex => cb(Left(ex))
            }
          }
          ()
        }
        .guarantee(CS.shift)
    }

  val token = "foo"
}

```
</details>

Also without fs2, only cats-effect as a dependency:

<details>
<summary>Code without fs2 (HTTP 1.1)</summary>

```scala
import java.net.URI
import java.net.http.HttpClient.Version
import java.net.http.HttpRequest.BodyPublishers
import java.net.http.HttpResponse.BodyHandlers
import java.net.http.{HttpClient, HttpRequest}
import java.time.{Instant, Duration => JDuration}
import java.util.concurrent.{CancellationException, CompletionException, CompletionStage}

import cats.effect._
import cats.effect.implicits._
import cats.implicits._

import scala.concurrent.duration._

object Main extends IOApp {

  override def run(args: List[String]): IO[ExitCode] =
    for {
      client <- IO(HttpClient.newHttpClient())
      runRequest = fromCompletionStage(
        IO(
          client.sendAsync(
            HttpRequest
              .newBuilder()
              .uri(URI.create("https://discordapp.com/api/gateway/bot"))
              .method("GET", BodyPublishers.noBody())
              .header("Authorization", s"Bot $token")
              .version(Version.HTTP_1_1)
              .build(),
            BodyHandlers.ofString()
          )
        )
      )
      start <- IO(Instant.now())
      ec <- (runRequest <* IO.sleep(5.seconds)).flatMap(s =>
        IO {
          println(s.statusCode)
          val now = Instant.now()
          println(s"[$now] ${JDuration.between(start, now).toSeconds} seconds")
        }
      ).foreverM
    } yield ec

  def fromCompletionStage[F[_], CF[x] <: CompletionStage[x], A](
      fcs: F[CF[A]]
  )(implicit F: Concurrent[F], CS: ContextShift[F]): F[A] =
    fcs.flatMap { cs =>
      F.async[A] { cb =>
          cs.handle[Unit] { (result, err) =>
            err match {
              case null => cb(Right(result))
              case _: CancellationException => ()
              case ex: CompletionException if ex.getCause ne null => cb(Left(ex.getCause))
              case ex => cb(Left(ex))
            }
          }
          ()
        }
        .guarantee(CS.shift)
    }

  val token = "foo"

}

```
</details>

If I use HTTP 2 instead of HTTP 1.1 in the second example, I can reproduce the `too many concurrent streams` issue, so this issue is definitely unrelated to #207.

<details>
<summary>Code without fs2 (HTTP 2)</summary>

```scala
import java.net.URI
import java.net.http.HttpClient.Version
import java.net.http.HttpRequest.BodyPublishers
import java.net.http.HttpResponse.BodyHandlers
import java.net.http.{HttpClient, HttpRequest}
import java.time.{Instant, Duration => JDuration}
import java.util.concurrent.{CancellationException, CompletionException, CompletionStage}

import cats.effect._
import cats.effect.implicits._
import cats.implicits._

import scala.concurrent.duration._

object Main extends IOApp {

  override def run(args: List[String]): IO[ExitCode] =
    for {
      client <- IO(HttpClient.newHttpClient())
      runRequest = fromCompletionStage(
        IO(
          client.sendAsync(
            HttpRequest
              .newBuilder()
              .uri(URI.create("https://discordapp.com/api/gateway/bot"))
              .method("GET", BodyPublishers.noBody())
              .header("Authorization", s"Bot $token")
              .version(Version.HTTP_2)
              .build(),
            BodyHandlers.ofPublisher()
          )
        )
      )
      start <- IO(Instant.now())
      ec <- (runRequest <* IO.sleep(5.seconds)).flatMap(s =>
        IO {
          println(s.statusCode)
          val now = Instant.now()
          println(s"[$now] ${JDuration.between(start, now).toSeconds} seconds")
        }
      ).foreverM
    } yield ec

  def fromCompletionStage[F[_], CF[x] <: CompletionStage[x], A](
      fcs: F[CF[A]]
  )(implicit F: Concurrent[F], CS: ContextShift[F]): F[A] =
    fcs.flatMap { cs =>
      F.async[A] { cb =>
          cs.handle[Unit] { (result, err) =>
            err match {
              case null => cb(Right(result))
              case _: CancellationException => ()
              case ex: CompletionException if ex.getCause ne null => cb(Left(ex.getCause))
              case ex => cb(Left(ex))
            }
          }
          ()
        }
        .guarantee(CS.shift)
    }

  val token = "foo"

}
```
</details>

I don't know if the freeze issue is fixed by using HTTP 2, or if the `too many streams` exception just occurs first.

<hr>

In addition to the synchronous "plain Java" version above, here also a version with `sendAsync`.

<details>
<summary>Code without fs2 (HTTP 2)</summary>

```scala
import java.net.*;
import java.net.http.*;
import java.net.http.HttpClient.Version;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.*;
import java.util.concurrent.*;

class Main {
  public static void main(String[] args) throws Exception {
    System.out.println("starting");
    var http = HttpClient.newHttpClient();
    var token = args[0];
    var req = HttpRequest.newBuilder()
                  .uri(URI.create("https://discordapp.com/api/gateway/bot"))
                  .header("Authorization", "Bot " + token)
                  .version(HttpClient.Version.HTTP_2)
                  .build();
    int s = 0;
    var fut = CompletableFuture.completedFuture(0);
    while (true) {
      Thread.sleep(5000);
      s += 5;
      final var ss = s;
      fut =
          fut.thenCompose(
                 $ -> http.sendAsync(req, HttpResponse.BodyHandlers.ofString()))
              .thenApply(res -> {
                System.out.println("status code " + res.statusCode());
                System.out.println(ss);
                return 0;
              });
    }
  }
}

```
</details>

Both HTTP 1.1 and HTTP 2 work fine, without any freezes or exceptions.

**Comment by amesgen** [comment] 2020-04-03 21:02
This GH issue is already pretty big, and we have two (probably unrelated subissues), and none of them are related to http4s or http4s-jdk-http-client directly. Do we want to move the discussion elsewhere?

**Comment by amesgen** [comment] 2020-04-03 21:12
Ha, I just got a freeze with this "plain Java" code:

<details>
<summary>Code</summary>

```
import java.net.*;
import java.net.http.*;
import java.net.http.HttpClient.Version;
import java.net.http.HttpRequest.BodyPublishers;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.*;
import java.util.concurrent.*;

class Main {
  public static void main(String[] args) throws Exception {
    System.out.println("starting");
    var http = HttpClient.newHttpClient();
    var token = args[0];
    var req = HttpRequest.newBuilder()
                  .uri(URI.create("https://discordapp.com/api/gateway/bot"))
                  .header("Authorization", "Bot " + token)
                  .version(HttpClient.Version.HTTP_2)
                  .build();
    int s = 0;
    var fut = CompletableFuture.completedFuture(0);
    while (true) {
      Thread.sleep(5000);
      s += 5;
      final var ss = s;
      fut =
          fut.thenCompose(
                 $ -> http.sendAsync(req, HttpResponse.BodyHandlers.ofPublisher()))
              .thenApply(res -> {
                System.out.println("status code " + res.statusCode());
                System.out.println(ss);
                return 0;
              });
    }
  }
}
```
</details>

Now this seems to indicate that the freeze issue is indeed a Java 11 issue.

@Billzabob Can you confirm this?

**Comment by Billzabob** [comment] 2020-04-03 22:46
Yep! That froze for me too after 1280 seconds.

**Comment by Billzabob** [comment] 2020-04-04 00:16
I tried modifying your example and changing `BodyHandlers.ofPublisher()` to `BodyHandlers.discarding()` and now it's been going for 2850 seconds without hanging. Think it could have something to do with that? I'll leave it running to make sure. I know nothing about `java.util.concurrent.Flow` though.

**Comment by amesgen** [comment] 2020-04-04 00:26
Yes, that is still confusing me:

 - When using `BodyPublishers.ofPublisher` like in the "intended connection leakage" example from [here](https://github.com/http4s/http4s-jdk-http-client/issues/200#issuecomment-608642324), it results in a `too many concurrent streams` exception. This seems very reasonable.
 - When using `BodyPublishers.ofPublisher` with the plain Java version, we get a freeze (I confirmed that it still is the SSL issue). This is weird, I would expect an `too many concurrent streams` exception.

But when using an "eager" `BodyPublisher` like `discarding` or `ofString`, the cats-effect version does freeze (see [here](https://github.com/http4s/http4s-jdk-http-client/issues/200#issuecomment-608228526)), although plain Java seems to work fine.

**Comment by Billzabob** [comment] 2020-04-04 02:23
Wow. That is extremely confusing. This type of stuff is such a pain to track down. Especially since it takes minutes or hours to determine if it's going to freeze or not.

**Comment by LolHens** [comment] 2020-08-09 19:26
I think I'm also having this issue with my simple one-file http-retry-proxy microservice:
https://github.com/LolHens/http-wait/blob/cd87c443e76812dbecaeae9b7c51f5004f6aa181/src/main/scala/de/lolhens/httpwait/Main.scala
I am not using websockets, just simple http requests. I run this as a graal native-image in a docker container.
This runs fine sometimes for a few days and sometimes for weeks but now and then it just locks up and I also get 100% cpu on the container.
Maybe this info helps to narrow it down. For now I will try switching to another client backend.

**Comment by amesgen** [comment] 2020-08-09 19:34
Thanks for reminding me of this issue @ LolHens 

Note that this issue is *not* caused by http4s-jdk-http-client, but rather by some weird interaction of cats-effect and TLSv1.3 stuff (maybe cats-effect only increases the likelihood of this TLS bug to occur). [src](https://github.com/http4s/http4s-jdk-http-client/issues/200#issuecomment-608642324)

There two easy workarounds (also see [our docs](https://jdk-http-client.http4s.org/stable#compatibility)):

 - Disable TLSv1.3 (also see [here](https://github.com/http4s/http4s-jdk-http-client/issues/200#issuecomment-607600926))
 - Use Java > 11

**Comment by LolHens** [comment] 2020-08-09 19:49
Thanks for the quick info! I will try disabling TLSv1.3 then.

**Closed** 2020-08-10 16:00 UTC
